export const items = [
  {
    id: Math.random(),
    title: "وجبه فطار",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "1.webp",
  },
  {
    id: Math.random(),
    title: "وجبه غدا",
    description: "وصف الغدا",
    price: "40 جنيه",
    category: "غداء",
    imgUrl: "2.webp",
  },
  {
    id: Math.random(),
    title: "وجبه عشا",
    description: "وصف العشا",
    price: "30 جنيه",
    category: "عشاء",
    imgUrl: "3.webp",
  },
  {
    id: Math.random(),
    title: "وجبه غدا ممتاز",
    description: "وصف الفطار",
    price: "20 جنيه",
    category: "فطار",
    imgUrl: "1.webp",
  },
  {
    id: Math.random(),
    title: "وجبه عشا درجه اولي",
    description: "وصف الغدا",
    price: "50 جنيه",
    category: "غداء",
    imgUrl: "2.webp",
  },
  {
    id: Math.random(),
    title: "وجبه فطار",
    description: "وصف العشا",
    price: "80 جنيه",
    category: "عشاء",
    imgUrl: "3.webp",
  },
  {
    id: Math.random(),
    title: "وجبه سناك",
    description: "وصف سناك",
    price: "80 جنيه",
    category: "سناك",
    imgUrl: "3.webp",
  },
  
];
